### ISSUE TITLE
Update the readme to mention package manager support?

### ISSUE THREAD

**Issue by andybak** [Merlin-san/EasyEventEditor#5]
I can see a package.json so I'm guessing that this can most easily be installed via UPM. If so might be worth mentioning this in the readme.

**Comment by MerlinVR** [comment]
Added a some documentation to the readme regarding the package manager, thanks!

**Comment by andybak** [comment]
You should be able to use the Github url directly in package manager. No need to download and unzip.

**Comment by MerlinVR** [comment]
Ah okay good to know, I'm usually using 2018.4 which doesn't have the add from git URL or tarball options.
