### ISSUE TITLE
using package manager failed

### ISSUE THREAD

**Issue by fight4dream** [Merlin-san/EasyEventEditor#6]
![image](https://user-images.githubusercontent.com/22952143/74805992-bc82c600-531f-11ea-8c67-a813f1fb2d43.png)
please upload also the meta files in order to import through package manager.

you can get the meta files by Edit -> Project Settings -> Editor -> Version Control mode = visible meta files
![image](https://user-images.githubusercontent.com/22952143/74806180-3d41c200-5320-11ea-965b-bf2a0722fac3.png)

**Comment by MerlinVR** [comment]
Resolved in 4d60f139bc61f7616f7cbca2df27e9f39a209bef thanks!
