### ISSUE TITLE
Dynamic Unity EventSystem functions with BaseEventData unselectable in Editor and existing linkages shown as <Missing>

### ISSUE THREAD

**Issue by cmlewis89** [Merlin-san/EasyEventEditor#7]
Repro::

Add an EventSystem to your Scene. Add an Event Trigger to an object (say a UnityEngine.UI.Image) and make a script with a method having the call signature:
```
public void OnDrag(BaseEventData dat)
{
   UnityEngine.Debug.Log("hello");
}
```

Disable EasyEventEditor, notice you can connect the Dynamic BaseEventData method like in the image below:
![image](https://user-images.githubusercontent.com/1067106/81038206-0b89c300-8e5a-11ea-8188-97eb4a1d1f1e.png)

Connect it.
Now enable EasyEventEditor. See that now the method shows as `<Missing>`.
![image](https://user-images.githubusercontent.com/1067106/81038483-01b48f80-8e5b-11ea-8e4b-86b76d84e637.png)

**Comment by MerlinVR** [comment]
Resolved in 1.0.2, thanks!
