### ISSUE TITLE
Missing meta files when install via OpenUPM

### ISSUE THREAD

**Issue by laicasaane** [Merlin-san/EasyEventEditor#8]
All meta files are missing and it makes the package unusable.

**Comment by JesseTG** [comment]
I think @Merlin-san has to push a new tag that includes the work in 4d60f13.

**Comment by JesseTG** [comment]
@Merlin-san Could you push a new tag, please?

**Comment by MerlinVR** [comment]
A new release has been published and tagged so this should be resolved, thanks!

**Comment by JesseTG** [comment]
Almost. https://github.com/Merlin-san/EasyEventEditor/issues/9

**Comment by JesseTG** [comment]
There we go. Beautiful! Thank you very much. Handy tool, I like it a lot.
