### ISSUE TITLE
Version mismatched

### ISSUE THREAD

**Issue by favoyang** [Merlin-san/EasyEventEditor#9]
Git tag v1.0.2
package.json 1.0.1

To fix: bump package.json  to 1.0.2, then retag it.

To automate the process of package release, please checkout
- Using GitHub Actions: https://medium.com/openupm/how-to-maintain-upm-package-part-2-f352fbf5f87c
- Using CLI which gives you more control: https://medium.com/openupm/how-to-maintain-upm-package-part-4-managing-package-release-with-cli-972ff5311163

**Comment by MerlinVR** [comment]
Fixed
